config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :kelass

root'welcomes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kela.rb
class Kela < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kelass_controller.rb
class KelassController < ApplicationController

	def new

	end


	def create
		@kelas = Kela.new(kela_params)
		@kelas.save
		redirect_to @kelas
	end


	private
	def kela_params
		params.require(:Kela).permit(:MataKuliah,:SKS,:jam,:ruangan,:hari,:jumlahMahasiswa)

	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController




	def index


	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kelass_helper.rb
module KelassHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/kelass/new.html.erb
<h1> Buat kelas </h1>


<%= form_for :kelas, url: kelass_index_path do |f| %>

	  <p>
	    <%= f.label :Mata_Kuliah %><br>
	    <%= f.text_field :MataKuliah %>
	  </p>
	 
	  <p>
	    <%= f.label :SKS %><br>
	    <%= f.text_field :SKS %>
	  </p>

	  <p>
	    <%= f.label :Jam %><br>
	    <%= f.select :Jam, [['07.30','07.30'],['10.00','10.00'],['13.20','13.20'],['15.50','15.50']] %>
	  </p>
	 
	  <p>
	    <%= f.label :Ruangan %><br>
	    <%= f.text_field :ruangan %>
	  </p>

	  <p>
	    <%= f.label :Hari %><br>
	    <%= f.select :hari, [['senin','senin'],['selasa','selasa'],['rabu','rabu'],['kamis','kamis'],['jumat','jumat']] %>
	  </p>

	  <p>
	    <%= f.label :Jumlah_Mahasiswa %><br>
	    <%= f.text_field :JumlahMahasiswa  %>
	  </p>

  <p>
    <%= f.submit %>
  </p>

 <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDev</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/index.html.erb
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><H1> Welcome to Universitas Ciputra </H1></title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 150px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SEP</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Daftar Kelas</h1>
                <p class="lead"></p>
                <ul class="list-unstyled">
                    
                </ul>
            </div>
            <div class="col-lg-2 text-center">
            	<button type="button" class="btn btn-default" class="btn btn-danger dropdown-toggle">        <li><a href="">Buat kelas</a></li>
    			</button>          			
            	           		  
           	</div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->




    <!-- jQuery Version 1.11.1 -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>